apiVersion: v1
kind: Service
metadata:
  name: istiocoredns
  namespace: istio-system
spec:
  selector:
    app: istiocoredns
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
